### ISSUE TITLE
Can't find PHPSESSID in aternos server inspect

### ISSUE THREAD

**Issue by ExtremSnek** [pritam20ps05/mcscraper#2]
I followed the instructions:

> goto the [aternos servers page](https://aternos.org/servers/) => click on any of your servers => right click and click on inspect => goto application section and click on cookies => select https://aternos.org/ => copy and paste the cookies according to the names of them mentioned in credentials.json bellow. Don't worry if some of them are not present just leave them blank the crucial ones are ATERNOS_SESSION and PHPSESSID.

I can find the ATERNOS_SESSION cookie but there is no PHPSESSID in sight. There seem to be a lot more cookies than in the reference image but the correct amount have the aternos.org domain.

**Comment by pritam20ps05** [comment]
there should be one. I took this picture now only see
![image](https://user-images.githubusercontent.com/49360491/152672838-592d8677-291c-4b56-96cd-64063c010404.png)

**Comment by pritam20ps05** [comment]
I got it I got it which browser are you using to get the cookies?

**Comment by pritam20ps05** [comment]
the thing is that other cookies don't matter that much except ATERNOS_SESSION and ATERNOS_SERVER so add whatever you are getting

**Comment by pritam20ps05** [comment]
@ExtremSnek has this issue been solved. If yes then i will close this issue. If there is no reply for 72 hrs then this issue will be closed.

**Comment by pritam20ps05** [comment]
The documentation has been updated in the commit 367f2531185bcf565bcfa7d47fe2cc714d7f3b13. And due to prolonged inactivity it has been assumed that the problem has been solved so closing this issue. But feel free to reopen it if necessary.

**Comment by pritam20ps05** [comment]
You don't need to use multiple cookies. Have a look at my 2nd comment only ATERNOS_SESSION is required. Also check the updated README

**Comment by ExtremSnek** [comment]
I've updated my credentials.json file to include only the discord bot token and ATERNOS_SESSION. 
I get this error when attempting to start the MC server: 
`"Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.", source:  (0)`

**Comment by pritam20ps05** [comment]
Is it only when starting or for every other command.

**Comment by pritam20ps05** [comment]
I guess it shouldn't be a problem as when opened from a normal browser the console shows the same warning. It is more of a warning than an error see this.
![image](https://user-images.githubusercontent.com/49360491/153740218-bc3429cf-1120-4156-a712-7225fe6c6e07.png)

**Comment by pritam20ps05** [comment]
Join my discord server link given in README

**Comment by pritam20ps05** [comment]
Problem further discussed on discord
