### ISSUE TITLE
Invalid Token

### ISSUE THREAD

**Issue by Technitium404** [pritam20ps05/mcscraper#3]
I am using replit and I used process.env.token
JSON file: 
`{`
  "secret_key": "<process.env.['token']>",
  "common_cookies": {
    "one": {
      "name": "process.env.['session']",
      "value": ""
    }
  }
}`

Error:

`Traceback (most recent call last):
  File "/home/runner/Aternos-API/venv/lib/python3.8/site-packages/discord/http.py", line 300, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "/home/runner/Aternos-API/venv/lib/python3.8/site-packages/discord/http.py", line 254, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "mcscraper/bot.py", line 96, in <module>
    bot.run(credentials["secret_key"])
  File "/home/runner/Aternos-API/venv/lib/python3.8/site-packages/discord/client.py", line 723, in run
    return future.result()
  File "/home/runner/Aternos-API/venv/lib/python3.8/site-packages/discord/client.py", line 702, in runner
    await self.start(*args, **kwargs)
  File "/home/runner/Aternos-API/venv/lib/python3.8/site-packages/discord/client.py", line 665, in start
    await self.login(*args, bot=bot)
  File "/home/runner/Aternos-API/venv/lib/python3.8/site-packages/discord/client.py", line 511, in login
    await self.http.static_login(token.strip(), bot=bot)
  File "/home/runner/Aternos-API/venv/lib/python3.8/site-packages/discord/http.py", line 304, in static_login
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.`

Help!

**Comment by pritam20ps05** [comment]
You are doing it the wrong way
```json
{
  "secret_key": "<Your actual bot token>",
  "common_cookies": {
    "one": {
      "name": "ATERNOS_SESSION",
      "value": "<Your aternoss session cookie>"
    }
  }
}
```

the values of entries within <> must be given directly and do not take them from environment. As its a json file and it can't fetch env vars by itself
eg:
```json
{
  "secret_key": "hjG-087HHMNghjBjkkjKJ573-jjNKJ4k43hk63JKLjJGJKCFczxKnvtCC",
  "common_cookies": {
    "one": {
      "name": "ATERNOS_SESSION",
      "value": "HBjhbHUYvgvsfsERCnbHJFDrtgLNKJygyuIKJbgCERX"
    }
  }
} 
```
i guess you got it

**Comment by pritam20ps05** [comment]
Also i looked up online and found that replit is a online code editor. Please use a offline one and do all the mentioned things in the README before launching it. The instructions has been made like that because it works by controlling an actual browser through apis so do it that way.

**Comment by Technitium404** [comment]
what should I use for it to be 24/7 for free
Not in PC

**Comment by pritam20ps05** [comment]
If you have a credit or debit card then you can get 1 year of free vps from service providers like linode, digital ocean etc. I personally use Alibaba cloud as it does not require any credit or debit card. Currently heroku is free but it gets blocked by cloudflare so you can't use it. I am trying to bypass it, till then use the mentioned technique

**Comment by pritam20ps05** [comment]
I added my discord server link to README join for detailed discussions

**Comment by pritam20ps05** [comment]
assuming problem solved
