### ISSUE TITLE
Failed to start Bot Service

### ISSUE THREAD

**Issue by Flohkiste** [pritam20ps05/mcscraper#4]
Hi,
I tried to start the bot but this happend.[](url
![Unbenannt](https://user-images.githubusercontent.com/76181281/153604033-2ad59628-a622-43ff-bfe5-8bac9b745e8c.PNG)
)

**Comment by pritam20ps05** [comment]
Have you tried it the normal way `python bot.py`. But i can see the problem
```bash
[Unit]
Description=Bot Service
After=multi-user.target
Conflicts=getty@tty1.service

[Service]
Type=simple
Restart=on-failure
WorkingDirectory=/<path to mcscraper folder>/mcscraper/
ExecStart=/<python interpreter bin folder>/python /<path to mcscraper folder>/mcscraper/bot.py
StandardInput=tty-force

[Install]
WantedBy=multi-user.target
```

here `<path to mcscraper folder>` must be something like /root/ and `<python interpreter bin folder>` must be something like /usr/bin/    
Everywhere in the README there are quotations in <> and they must be replaced by real life values

**Comment by pritam20ps05** [comment]
please send the path to the mcscraper folder.

**Comment by Flohkiste** [comment]
![image](https://user-images.githubusercontent.com/76181281/153706560-77d30161-c88e-48c7-9bd7-f66c20109ac3.png)
i tried it idk what i'm doing wrong is there a video tutorial or something?

**Comment by pritam20ps05** [comment]
See you made a mistake again first run `which python` in your terminal and tell me the output. Believe me there is no way it will not work as my server still uses it and it is totally functional. Also I am using the mentioned way only so it should work.

See this example
![image](https://user-images.githubusercontent.com/49360491/153715817-8ab649a6-3648-4e02-a421-4d87d542b7c3.png)

**Comment by Flohkiste** [comment]
The Output is  /usr/bin/python
This is what stands in the bot.service file:
![image](https://user-images.githubusercontent.com/76181281/153717211-54b81ecf-3fcc-45aa-889c-446cf64f5c96.png)

**Comment by pritam20ps05** [comment]
Yea is it working now?

**Comment by Flohkiste** [comment]
![image](https://user-images.githubusercontent.com/76181281/153744158-80beebe5-6a6f-4ae9-bf07-06b4c4a7ce44.png)
Still not working

**Comment by pritam20ps05** [comment]
Are you sure that your mcscraper folder location is correct. Can you connect me on discord? I am giving off the link in the README

**Comment by pritam20ps05** [comment]
The README was updated to contain the guild link

**Comment by pritam20ps05** [comment]
problem solved on discord
